plugins {
    id 'java'
    id 'io.spring.dependency-management'
}

group = 'com.paybook'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.3"
    }
}

test {
    useJUnitPlatform()
}
