spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/paymentdb
    driver-class-name: org.postgresql.Driver
    username: paybook
    password: paybook
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8081

payment:
  order-service:
    base-url: http://localhost:8080
